services:
  - type: web
    name: skillswap-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: "https://skill-swap-frontend-iota.vercel.app"